config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope module: 'web' do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get '/logout', to: 'auth#destroy', as: 'logout'

    resources :repositories, only: %i[index new create show] do
      resources :checks, only: %i[create show], module: :repository
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  # Defines the root path route ("/")
  root 'web/welcome#index'

  namespace :api do
    resources :checks, only: [:create]
  end
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  belongs_to :user
  has_many :checks, class_name: 'Repository::Check', dependent: :destroy

  extend Enumerize
  enumerize :language, in: %w[Ruby JavaScript], default: 'Ruby', predicates: true

  validates :github_id, presence: true
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  self.table_name = 'repository_checks'

  belongs_to :repository
  has_many :linter_errors, dependent: :destroy

  aasm column: :aasm_state do
    state :created, initial: true
    state :checking
    state :finished
    state :failed

    event :start_check do
      transitions from: :created, to: :checking
    end

    event :complete_check do
      transitions from: :checking, to: :finished
    end

    event :fail_check do
      transitions from: %i[created checking], to: :failed
    end
  end

  def commit_link
    "https://github.com/#{repository.full_name}/commit/#{commit_id}"
  end
end

app/controllers/repository/checks_controller.rb
# frozen_string_literal: true

require 'open3'

class Repository::ChecksController < ApplicationController
  before_action :authenticate_user!
  def show
    @repository = Repository.owner(current_user).find(params[:repository_id])
    @check = @repository.checks.find(params[:id])
    authorize @check
  end

  def create
    @repository = Repository.find(params[:repository_id])
    @check = @repository.checks.new

    if @check.save
      redirect_to repository_path(@repository), notice: I18n.t('check.created')
      RepositoryCheckJob.perform_later(@check.id, @repository.id)
    else
      redirect_to repository_path(@repository), alert: I18n.t('check.error')
    end
  end

  private

  def authenticate_user!
    redirect_to root_path, alert: I18n.t('user.auth') unless current_user
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = current_user.repositories
  end

  def show
    @repository = current_user.repositories.find(params[:id])

    @checks = @repository.checks.order(created_at: :desc).limit(15)
  end

  def new
    client = ApplicationContainer[:github_client].new(access_token: current_user.token, auto_paginate: true)
    all_repositories = client.repos
    languages = %w[Ruby JavaScript]

    @repositories = all_repositories.select { |repo| languages.include?(repo.language) }
  end

  def create
    github_id = params[:repository][:github_id].to_i
    current_user.repositories.create(github_id:)
    Repository::FetchDataJob.perform_later(github_id, current_user.id)
    redirect_to repositories_path, notice: I18n.t('repository.created')
  end
end

app/controllers/web/repository/checks_controller.rb
# frozen_string_literal: true

require 'open3'

class Web::Repository::ChecksController < ApplicationController
  before_action :authenticate_user!
  def show
    @repository = current_user.repositories.find(params[:repository_id])
    @check = @repository.checks.find(params[:id])
  end

  def create
    @repository = current_user.repositories.find(params[:repository_id])
    @check = @repository.checks.new

    if @check.save
      redirect_to repository_path(@repository), notice: I18n.t('check.created')
      Repository::CheckJob.perform_later(@check.id)
    else
      redirect_to repository_path(@repository), alert: I18n.t('check.error')
    end
  end
end

app/views/web/repositories/index.html.slim
.container.border.p-4.rounded.mt-4
  .table-responsive
    table.table
      = link_to t('repository.add'), new_repository_path, class: 'btn btn-primary'
      p
      thead
        tr
          th = t('check.id')
          th = t('check.commit')
          th = t('check.latest_check')

      tbody
        - @repositories.each do |repository|
          tr
            td = link_to repository.name, repository_path(repository)
            td = repository.language
            - if repository.checks.any?
              td = repository.checks.last.aasm_state
            - else
              td = t('repository.no_checks')

app/views/web/repositories/new.html.slim
.container.border.p-4.rounded.mt-4
  = form_with url: repositories_path, method: :post, class: 'w-100' do |form|
    .form-group
      = form.label :repository, 'Github', class: 'form-label'
      = form.select :github_id, @repositories.map { |repo| [repo.full_name, repo.id] }, {}, name: 'repository[github_id]', class: 'form-control w-100'
    .mt-3
      = form.submit t('repository.choose'), class: 'btn btn-primary w-100'

app/views/web/repositories/show.html.slim
.container.border.p-4.rounded.mt-4
  .repository-info
    p
      strong = "#{t('repository.name')} :"
      span(style='margin-left: 10px; font-weight: normal;') = @repository.full_name

    p
      strong = "#{t('repository.language')} :"
      span(style='margin-left: 10px; font-weight: normal;') = @repository.language

    p
      strong = "#{t('check.created_at')} :"
      span(style='margin-left: 10px; font-weight: normal;') = @repository.created_at.strftime('%Y-%m-%d %H:%M:%S')

    = button_to t('check.create'), repository_checks_path(@repository), class: 'btn btn-primary'

.container.border.p-4.rounded.mt-4
  .table-responsive
    table.table
      thead
        tr
          th = t('check.id')
          th = t('check.commit')
          th = t('check.latest_check')

      tbody
        - @checks.each do |check|
          tr
            td = link_to check.id, repository_check_path(@repository, check)
            td = link_to check.commit_id, check.commit_link
            td = check.aasm_state.capitalize