config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope module: 'web' do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get '/logout', to: 'auth#destroy', as: 'logout'

    resources :repositories, only: %i[index new create show] do
      resources :checks, only: %i[create show], module: :repository
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  # Defines the root path route ("/")
  root 'web/welcome#index'

  namespace :api do
    resources :checks, only: [:create]
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:title) || 'Rails Project 66'
    meta name='viewport' content='width=device-width,initial-scale=1'
    meta name='apple-mobile-web-app-capable' content='yes'
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    link rel='manifest' href='/manifest.json'
    link rel='icon' href='/icon.png' type='image/png'
    link rel='icon' href='/icon.svg' type='image/svg+xml'
    link rel='apple-touch-icon' href='/icon.png'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

  body
    - flash.each do |key, message|
      - if key == 'notice'
        .alert.alert-success.border-success
          = message
      - elsif key == 'alert'
        .alert.alert-danger.border-danger.role = alert
          = message

    .page-container
      header.navbar.navbar-expand-lg.navbar-light.bg-light
        nav.container-fluid
          .navbar-header.d-flex.align-items-center
            = link_to t('user.home'), root_path, class: 'navbar-brand text-primary text-decoration-none'
            = link_to t('repository.repositories'), repositories_path, class: 'navbar-brand text-primary text-decoration-none'

          - if current_user
            .ms-auto.d-flex.align-items-center
              .navbar-text.text-primary.font-weight-bold.fs-4
                = current_user.email
              .navbar-text
                = link_to t('user.logout'), logout_path, method: :delete, class: 'navbar-brand text-primary text-decoration-none'
          - else
            = button_to t('user.login'), auth_request_path('github'), data: { turbo: false }, method: :post, class: 'navbar-brand text-primary text-decoration-none'
    = yield